CREATE TABLE gender(id VARCHAR(36) NOT NULL)
ALTER TABLE gender ADD version BIGINT NOT NULL DEFAULT 0
ALTER TABLE gender ADD name VARCHAR(255) DEFAULT '<empty>'
ALTER TABLE gender ADD description VARCHAR(255)

ALTER TABLE gender ADD PRIMARY KEY(id)
ALTER TABLE gender ADD UNIQUE(name)


CREATE TABLE customer(id VARCHAR(36) NOT NULL, gender_id VARCHAR(36) NOT NULL)
ALTER TABLE customer ADD version BIGINT NOT NULL  DEFAULT 0
ALTER TABLE customer ADD given_name VARCHAR(255) NOT NULL DEFAULT '<empty>'
ALTER TABLE customer ADD family_name VARCHAR(255) NOT NULL DEFAULT '<empty>'
ALTER TABLE customer ADD email VARCHAR(255) NOT NULL DEFAULT '<empty>'
ALTER TABLE customer ADD phone_number VARCHAR(255)

ALTER TABLE customer ADD PRIMARY KEY(id)
ALTER TABLE customer ADD FOREIGN KEY(gender_id) REFERENCES gender(id)
ALTER TABLE customer ADD UNIQUE(email)

